language: node_js

node_js:
  - "6"
  - "7"

sudo: false

jobs:
  include:
    - stage: validate
      script:
        - yarn lint
        - yarn test

    - stage: release
      node_js: "7"
      script:
        - yarn build
        # - npm publish .
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          branch: master
          tags: true
          node: "7"

notifications:
  email:
    tom@x-c-o-d-e.com
