language: node_js

node_js: ['6', '7', '8']

install:
- yarn install

script:
- yarn lint
- yarn build
- yarn test

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" > ~/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish .
  on:
    tags: true

notifications:
  email:
    tom@x-c-o-d-e.com
